Move some stances around in the ci scripts

diff --git a/templates/github/.github/workflows/scripts/install.sh.j2 b/templates/github/.github/workflows/scripts/install.sh.j2
--- a/templates/github/.github/workflows/scripts/install.sh.j2
+++ b/templates/github/.github/workflows/scripts/install.sh.j2
@@ -2,23 +2,30 @@
 
 {% include 'header.j2' %}
 
+set -euv
+
 # make sure this script runs at the repo root
 cd "$(dirname "$(realpath -e "$0")")"/../../..
 REPO_ROOT="$PWD"
 
-set -euv
-
 source .github/workflows/scripts/utils.sh
-
-PLUGIN_VERSION="$(bump-my-version show current_version | tail -n -1 | python -c 'from packaging.version import Version; print(Version(input()))')"
-PLUGIN_SOURCE="./{{ plugin_name }}/dist/{{ plugin_name | snake }}-${PLUGIN_VERSION}-py3-none-any.whl"
-
-export PULP_API_ROOT="{{ api_root }}"
 
 PIP_REQUIREMENTS=("{{ cli_package }}")
 
 # This must be the **only** call to "pip install" on the test runner.
 pip install ${PIP_REQUIREMENTS[*]}
+
+if [[ "$TEST" = "s3" ]]; then
+for i in {1..3}
+do
+  ansible-galaxy collection install "amazon.aws:8.1.0" && s=0 && break || s=$? && sleep 3
+done
+if [[ $s -gt 0 ]]
+then
+  echo "Failed to install amazon.aws"
+  exit $s
+fi
+fi
 
 {% if test_cli -%}
 # Check out the {{ cli_package }} branch matching the installed version.
@@ -28,164 +35,7 @@ git clone --depth 1 --branch "$PULP_CLI_VERSION" {{ cli_repo }} ../{{ cli_packag
 
 cd .ci/ansible/
 
-{%- set PULPCORE_PREFIX = "" if plugin_name == "pulpcore" else " pulpcore" %}
-{%- if test_s3 %}
-if [ "$TEST" = "s3" ]; then
-  PLUGIN_SOURCE="${PLUGIN_SOURCE}{{ PULPCORE_PREFIX }}[s3]"
-fi
-{%- endif %}
-{%- if test_azure %}
-if [ "$TEST" = "azure" ]; then
-  PLUGIN_SOURCE="${PLUGIN_SOURCE}{{ PULPCORE_PREFIX }}[azure]"
-fi
-{%- endif %}
-{%- if test_gcp %}
-if [ "$TEST" = "gcp" ]; then
-  PLUGIN_SOURCE="${PLUGIN_SOURCE}{{ PULPCORE_PREFIX }}[google]"
-fi
-{%- endif %}
-
-cat >> vars/main.yaml << VARSYAML
-image:
-  name: pulp
-  tag: "ci_build"
-plugins:
-  - name: {{ plugin_name }}
-    source: "${PLUGIN_SOURCE}"
-VARSYAML
-if [[ -f ../../ci_requirements.txt ]]; then
-  cat >> vars/main.yaml << VARSYAML
-    ci_requirements: true
-VARSYAML
-fi
-if [ "$TEST" = "pulp" ]; then
-  cat >> vars/main.yaml << VARSYAML
-    upperbounds: true
-VARSYAML
-fi
-{%- if test_lowerbounds %}
-if [ "$TEST" = "lowerbounds" ]; then
-  cat >> vars/main.yaml << VARSYAML
-    lowerbounds: true
-VARSYAML
-fi
-{%- endif %}
-
-cat >> vars/main.yaml << VARSYAML
-{%- if extra_files %}
-extra_files:
-  {%- for item in extra_files %}
-  - origin: "{{ item.origin }}"
-    destination: "{{ item.destination }}"
-  {%- endfor %}
-{%- endif %}
-services:
-  - name: pulp
-    image: "pulp:ci_build"
-    volumes:
-      - ./settings:/etc/pulp
-      - ./ssh:/keys/
-      - ~/.config:/var/lib/pulp/.config
-      - ../../../pulp-openapi-generator:/root/pulp-openapi-generator
-    env:
-      PULP_WORKERS: "4"
-      PULP_HTTPS: "{{ 'true' if pulp_scheme == 'https' else 'false' }}"
-VARSYAML
-
-cat >> vars/main.yaml << VARSYAML
-pulp_env: {{ pulp_env | tojson }}
-pulp_settings: {{ pulp_settings | tojson }}
-pulp_scheme: {{ pulp_scheme }}
-{%- if ci_base_image.count(":") %}
-pulp_default_container: {{ ci_base_image }}
-{% else %}
-pulp_default_container: {{ ci_base_image + ":latest" }}
-{% endif -%}
-VARSYAML
-
-{%- if docker_fixtures %}
-
-SCENARIOS=("pulp" "performance" "azure" "gcp" "s3" "generate-bindings" "lowerbounds")
-if [[ " ${SCENARIOS[*]} " =~ " ${TEST} " ]]; then
-  sed -i -e '/^services:/a \
-  - name: pulp-fixtures\
-    image: docker.io/pulp/pulp-fixtures:latest\
-    env: {BASE_URL: "http://pulp-fixtures:8080"}' vars/main.yaml
-
-  export REMOTE_FIXTURES_ORIGIN="http://pulp-fixtures:8080"
-fi
-{%- endif %}
-
-{%- if test_s3 %}
-
-if [ "$TEST" = "s3" ]; then
-  export MINIO_ACCESS_KEY=AKIAIT2Z5TDYPX3ARJBA
-  export MINIO_SECRET_KEY=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
-  sed -i -e '/^services:/a \
-  - name: minio\
-    image: minio/minio\
-    env:\
-      MINIO_ACCESS_KEY: "'$MINIO_ACCESS_KEY'"\
-      MINIO_SECRET_KEY: "'$MINIO_SECRET_KEY'"\
-    command: "server /data"' vars/main.yaml
-  sed -i -e '$a s3_test: true\
-minio_access_key: "'$MINIO_ACCESS_KEY'"\
-minio_secret_key: "'$MINIO_SECRET_KEY'"\
-pulp_scenario_settings: {{ pulp_settings_s3 | tojson }}\
-pulp_scenario_env: {{ pulp_env_s3 | tojson }}\
-' vars/main.yaml
-
-  {%- if test_reroute %}
-  export PULP_API_ROOT="/rerouted/djnd/"
-  {%- endif %}
-fi
-{%- endif %}
-
-{%- if test_azure %}
-
-if [ "$TEST" = "azure" ]; then
-  sed -i -e '/^services:/a \
-  - name: ci-azurite\
-    image: mcr.microsoft.com/azure-storage/azurite\
-    volumes:\
-      - ./azurite:/etc/pulp\
-    command: "azurite-blob --skipApiVersionCheck --blobHost 0.0.0.0"' vars/main.yaml
-  sed -i -e '$a azure_test: true\
-pulp_scenario_settings: {{ pulp_settings_azure | tojson }}\
-pulp_scenario_env: {{ pulp_env_azure | tojson }}\
-' vars/main.yaml
-fi
-{%- endif %}
-
-{%- if test_gcp %}
-
-if [ "$TEST" = "gcp" ]; then
-  mkdir -p cigcp
-  cd cigcp
-  openssl req -newkey rsa:2048 -x509 -nodes -keyout gcpkey.pem -new -out gcpcert.pem -sha256 -days 365 -addext "subjectAltName=DNS:ci-gcp" -subj "/C=CO/ST=ST/L=LO/O=OR/OU=OU/CN=CN"
-  sudo cp gcpcert.pem /usr/local/share/ca-certificates/gcpcert.crt
-  sudo dpkg-reconfigure ca-certificates
-  cd ..
-  sed -i -e '/^services:/a \
-  - name: ci-gcp\
-    image: fsouza/fake-gcs-server\
-    volumes:\
-      - storage_data:/etc/pulp\
-    command: "{% if pulp_scheme == "https" %} -cert-location /etc/pulp/gcpcert.pem {% else %} -scheme http{% endif %}"' vars/main.yaml
-  sed -i -e '$a gcp_test: true\
-pulp_scenario_settings: {{ pulp_settings_gcp | tojson }}\
-pulp_scenario_env: {{ pulp_env_gcp | tojson }}\
-' vars/main.yaml
-fi
-{%- endif %}
-
-echo "PULP_API_ROOT=${PULP_API_ROOT}" >> "$GITHUB_ENV"
-
-if [ "${PULP_API_ROOT:-}" ]; then
-  sed -i -e '$a api_root: "'"$PULP_API_ROOT"'"' vars/main.yaml
-fi
-
-pulp config create --base-url {{ pulp_scheme }}://pulp{% if pulp_scheme != 'https' %} --no-verify-ssl{% endif %} --api-root "$PULP_API_ROOT" --username "admin" --password "password"
+pulp config create --base-url {{ pulp_scheme }}://pulp{% if pulp_scheme != 'https' %} --no-verify-ssl{% endif %} --api-root "${PULP_API_ROOT}" --username "admin" --password "password"
 {% if test_cli -%}
 cp ~/.config/pulp/cli.toml "${REPO_ROOT}/../{{ cli_package }}/tests/cli.toml"
 {%- endif %}
@@ -227,6 +77,18 @@ if [[ "$TEST" = "azure" ]]; then
   az storage container create --name pulp-test --connection-string $AZURE_STORAGE_CONNECTION_STRING
 fi
 
-echo ::group::PIP_LIST
-cmd_prefix bash -c "pip3 list"
-echo ::endgroup::
+# Needed for some functional tests
+cmd_prefix bash -c "echo '%wheel        ALL=(ALL)       NOPASSWD: ALL' > /etc/sudoers.d/nopasswd"
+cmd_prefix bash -c "usermod -a -G wheel pulp"
+{%- if disabled_redis_runners %}
+
+# In some scenarios we want to simulate a failed redis cache.
+if [[ " {{ " ".join(disabled_redis_runners) }} " =~ " ${TEST} " ]]; then
+  cmd_prefix bash -c "s6-rc -d change redis"
+  echo "The Redis service was disabled for $TEST"
+fi
+{%- endif %}
+
+# Lots of plugins try to use this path, and throw warnings if they cannot access it.
+cmd_prefix mkdir /.pytest_cache
+cmd_prefix chown pulp:pulp /.pytest_cache
