Build bindings artifacts in build step

diff --git a/templates/github/.github/workflows/scripts/script.sh.j2 b/templates/github/.github/workflows/scripts/script.sh.j2
--- a/templates/github/.github/workflows/scripts/script.sh.j2
+++ b/templates/github/.github/workflows/scripts/script.sh.j2
@@ -53,57 +53,62 @@ password password
 # Some commands like ansible-galaxy specifically require 600
 cmd_prefix bash -c "chmod 600 ~pulp/.netrc"
 
-# Generate and install binding
-pushd ../pulp-openapi-generator
-# Use app_label to generate api.json and package to produce the proper package name.
+# Generate bindings
+###################
 
-if [ "$(jq -r '.domain_enabled' <<<"$REPORTED_STATUS")" = "true" ]
-then
+touch bindings_requirements.txt
+pushd ../pulp-openapi-generator
+  # Use app_label to generate api.json and package to produce the proper package name.
+
   # Workaround: Domains are not supported by the published bindings.
-  # Generate new bindings for all packages.
-  for item in $(jq -r '.versions[] | tojson' <<<"$REPORTED_STATUS")
-  do
-    echo $item
-    COMPONENT="$(jq -r '.component' <<<"$item")"
-    VERSION="$(jq -r '.version' <<<"$item")"
-    # On older status endpoints, the module was not provided, but the package should be accurate
-    # there, because we did not merge plugins into pulpcore back then.
-    MODULE="$(jq -r '.module // (.package|gsub("-"; "_"))' <<<"$item")"
-    PACKAGE="${MODULE%%.*}"
-    cmd_prefix pulpcore-manager openapi --bindings --component "${COMPONENT}" > api.json
-    ./gen-client.sh api.json "${COMPONENT}" python "${PACKAGE}"
-    cmd_prefix pip3 install "/root/pulp-openapi-generator/${PACKAGE}-client"
-    sudo rm -rf "./${PACKAGE}-client"
-  done
-else
   # Sadly: Different pulpcore-versions aren't either...
-  for item in $(jq -r '.versions[]
-    {%- for plugin in plugins -%}
-    | select(.component!="{{ plugin.app_label }}")
-    {%- endfor -%}
-    | tojson' <<<"$REPORTED_STATUS")
+  # So we exclude the prebuilt ones only for domains disabled.
+  if [ "$(jq -r '.domain_enabled' <<<"${REPORTED_STATUS}")" = "true" ] || [ "$(jq -r '.online_workers[0].pulp_href|startswith("/pulp/api/v3/")' <<< "${REPORTED_STATUS}")" = "false" ]
+  then
+    BUILT_CLIENTS=""
+  else
+    BUILT_CLIENTS="{% for plugin in plugins %} {{ plugin.app_label }}{% endfor %} "
+  fi
+
+  for ITEM in $(jq -r '.versions[] | tojson' <<<"${REPORTED_STATUS}")
   do
-    echo $item
-    COMPONENT="$(jq -r '.component' <<<"$item")"
-    VERSION="$(jq -r '.version' <<<"$item")"
+    COMPONENT="$(jq -r '.component' <<<"${ITEM}")"
+    VERSION="$(jq -r '.version' <<<"${ITEM}" | python3 -c "from packaging.version import Version; print(Version(input()))")"
     # On older status endpoints, the module was not provided, but the package should be accurate
     # there, because we did not merge plugins into pulpcore back then.
-    MODULE="$(jq -r '.module // (.package|gsub("-"; "_"))' <<<"$item")"
+    MODULE="$(jq -r '.module // (.package|gsub("-"; "_"))' <<<"${ITEM}")"
     PACKAGE="${MODULE%%.*}"
-    cmd_prefix pulpcore-manager openapi --bindings --component "${COMPONENT}" > api.json
-    ./gen-client.sh api.json "${COMPONENT}" python "${PACKAGE}"
-    cmd_prefix pip3 install "/root/pulp-openapi-generator/${PACKAGE}-client"
-    sudo rm -rf "./${PACKAGE}-client"
+    if [[ ! " ${BUILT_CLIENTS} " =~ "${COMPONENT}" ]]
+    then
+      rm -rf "./${PACKAGE}-client"
+      cmd_prefix pulpcore-manager openapi --bindings --component "${COMPONENT}" > "${COMPONENT}-api.json"
+      ./gen-client.sh "${COMPONENT}-api.json" "${COMPONENT}" python "${PACKAGE}"
+      pushd "${PACKAGE}-client"
+        python setup.py sdist bdist_wheel --python-tag py3
+      popd
+    else
+      if [ ! -f "${PACKAGE}-client/dist/${PACKAGE}_client-${VERSION}-py3-none-any.whl" ]
+      then
+        ls -lR "${PACKAGE}-client/"
+        echo "Error: Client bindings for ${COMPONENT} not found."
+        echo "File ${PACKAGE}-client/dist/${PACKAGE}_client-${VERSION}-py3-none-any.whl missing."
+        exit 1
+      fi
+    fi
+    echo "/root/pulp-openapi-generator/${PACKAGE}-client/dist/${PACKAGE}_client-${VERSION}-py3-none-any.whl" >> "../{{ plugin_name }}/bindings_requirements.txt"
   done
-fi
 popd
 
-# At this point, this is a safeguard only, so let's not make too much fuzz about the old status format.
-echo "$REPORTED_STATUS" | jq -r '.versions[]|select(.package)|(.package|sub("_"; "-")) + "-client==" + .version' > bindings_requirements.txt
+# Install test requirements
+###########################
+
+# Add a safeguard to make sure the proper versions of the clients are installed.
+echo "$REPORTED_STATUS" | jq -r '.versions[]|select(.package)|(.package|sub("_"; "-")) + "-client==" + .version' > bindings_constraints.txt
 cmd_stdin_prefix bash -c "cat > /tmp/unittest_requirements.txt" < unittest_requirements.txt
 cmd_stdin_prefix bash -c "cat > /tmp/functest_requirements.txt" < functest_requirements.txt
 cmd_stdin_prefix bash -c "cat > /tmp/bindings_requirements.txt" < bindings_requirements.txt
-cmd_prefix pip3 install -r /tmp/unittest_requirements.txt -r /tmp/functest_requirements.txt -r /tmp/bindings_requirements.txt
+cmd_stdin_prefix bash -c "cat > /tmp/bindings_constraints.txt" < bindings_constraints.txt
+cmd_prefix pip3 install -r /tmp/unittest_requirements.txt -r /tmp/functest_requirements.txt -r /tmp/bindings_requirements.txt -c /tmp/bindings_constraints.txt
 
 CERTIFI=$(cmd_prefix python3 -c 'import certifi; print(certifi.where())')
 cmd_prefix bash -c "cat /etc/pulp/certs/pulp_webserver.crt >> '$CERTIFI'"
